meta_product_name: "Recruit.me"
meta_title: "Recruit.me - Your Skills, Your Move"
meta_description: "Recruit.me is an application to help managers find talent easily within their organisation and to help employees discover new job opportunities."
meta_image: "Recruitmelogo_big.png" # should exist in `app/assets/images/`
twitter_account: "@Recruit.me"   # required for Twitter Cards
